# Generated by Django 3.2.16 on 2023-01-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_auto_20230103_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='products',
        ),
    ]
