# Generated by Django 3.2.16 on 2023-01-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_remove_stock_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AddField(
            model_name='stock',
            name='products',
            field=models.ManyToManyField(related_name='stocks', through='logistic.StockProduct', to='logistic.Product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='address',
            field=models.CharField(max_length=200, unique=True, verbose_name='Адрес склада'),
        ),
    ]
