# Generated by Django 3.2.16 on 2023-01-03 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_auto_20230103_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='logistic.stock', unique=True),
        ),
    ]
